### ISSUE TITLE
KEGG Pathways

### ISSUE THREAD

**Issue by nmank** [cwieder/sspa-in-metabolomics#1]
Hello,

I couldn't find the pathways from KEGG in the directory:
    https://github.com/cwieder/sspa-in-metabolomics/tree/main/pathway_databases 

In the manuscript you say the pathways 
    "were downloaded using the KEGG REST API (https://www.kegg.jp/kegg/ rest/keggapi.html)."

Do you have a KEGG pathway file somewhere or any hints for how to access pathways with KEGG metabolite identifiers using the KEGG REST API?

Thanks,
Nate

**Comment by cwieder** [comment]
Hi Nate,

Unfortunately we can't distribute KEGG pathway files as you need an academic license to access these unlike Reactome which are freely available. But you could download them yourself using the API via our new toolkit '[sspa](https://github.com/cwieder/py-ssPA)'. Check out the tutorials [here](https://cwieder.github.io/py-ssPA/tutorials/) and please don't hesitate to get in touch if you experience any issues. 

An example of the Python code to download the KEGG metabolic pathways for mouse would be like so:
```
!pip install sspa==0.2.2

import sspa

kegg_mouse_latest = sspa.process_kegg("mmu", download_latest=True, filepath=".")
```

This can take around 10 minutes for KEGG due to the API queries, whereas downloading Reactome is much faster. The KEGG release number will be included in the downloaded file name.
